### PR TITLE
Use EuiBadge for combobox pilling

### PR DESCRIPTION
**Pull request by snide**
Hey @cjcenizal. Didn't want to slow you down since you're on a tear. I went ahead and made the combo box pills utilize the badge component. That was the original idea when I rebuilt badges, and i just never updated my original prototype.

Should have the following benefits

* Less maintenance, since badges have since gotten all the abilities of these pills.
* You can pass a color to them now. Like badges, these can either be a named value or a hex. Primarily I'd like something like this for nathan's tagging system, though im guessing coloring would be helpful in visualization bits as well.
* Badges should take up less space than the pills, so hopefully there's some more room now.

~~I'll probably pass something similar to the actual list options as well, so the colors show there in the dropdown, but that part can always come in later. I just figured I'd work through the big piece before we went down a specific road.~~ Did this too.

Nice work with the styling btw. It's hard to get all the pixels to line up with all the wrapping / truncating and what not. Definitely one of the more pixel pushy components we have.

### CODE REVIEW

**Comment by snide** [comment]
Also did some minor cleanup of the grouping to make it pop a bit more.

image

**Comment by snide** [comment]
Added the colors to the dropdown too.

image

**Comment by cjcenizal** [comment]
Thanks for doing this @snide! Looks great. I'll review the code and merge this in today.

**Review by cjcenizal — COMMENTED** [review]
This is awesome. I think everything looks great, but I think we should either revert the commit that added colors to the options (c35553c351a3d3203572b4d44c3dbf0faf06173a), or adjust it so that we have a EuiSwatch component or something similar which can support the different colors you want to show. Then we can merge this and I'll add a `renderOption` prop to EuiComboBox so that consumers can specify how each option renders. I'll update the example you've added to use this prop with EuiSwatch, to result in the same thing you have here. Wdyt?

**Comment by snide** [comment]
@cjcenizal I can do that. I won't get to it till the afternoon though if that's ok.

**Comment by snide** [comment]
Meaning I can make the swatch its own component. Where do you think that should live though? One option I could also do it just make `EuiIcon` accept hex colors, and then we could use the `dot` for the color here. Then we don't need an extra component and icons would be a little more flexible.

Lemme know and I'll set it up.

**Comment by cjcenizal** [comment]
Adding this functionality to EuiIcon sounds great, then we can just use EuiHealth in the `renderOption` definition. I'm not blocked on this so there's no rush. Thanks.

**Comment by snide** [comment]
OK @cjcenizal, I removed the object_list stuff and made `EuiIcon` accept hex values. Also added a validator to both badge and icon that checks to make sure the passed color is either one of the palette defined ones or a valid hex value.

Let me know if there's more you need.

**Comment by cjcenizal** [comment]
Looks good! Ready for me to merge this?

**Comment by snide** [comment]
@cjcenizal yeah, it's all done now.

**Pull request merged**
